apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-07-08T06:02:21Z"
  generation: 1
  labels:
    app: n1
  name: n1
  namespace: default
