apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T06:03:22Z"
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "415320"
  uid: c0007002-178f-44ca-8413-eb94c2c72970
spec:
  clusterIP: 10.233.50.87
  clusterIPs:
  - 10.233.50.87
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30138
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
